// THIS FILE WILL BE OVERWRITTEN BY DEV-C++!
// DO NOT EDIT!

#ifndef BBMAN_PRIVATE_H
#define BBMAN_PRIVATE_H

// VERSION DEFINITIONS
#define VER_STRING	"3.0.1.0"
#define VER_MAJOR	3
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"BBMan - BBS/SSH/SFTP/Telnet Client"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"BBMan"
#define PRODUCT_VERSION	""

#endif //BBMAN_PRIVATE_H
