# Project: BBMan
# Makefile created by Dev-C++ 4.9.9.0

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = BBMan_private.res
OBJ  = obj/bookmark.o obj/common.o obj/ds.o obj/editterm_win.o obj/frm_editterm.o obj/frm_telnet.o obj/login.o obj/main.o obj/scd_editterm.o obj/scd_gtk_textctrl.o obj/scd_socket.o obj/scd_tabctrl.o obj/scd_telnet.o obj/scd_terminal.o obj/telnet_panel.o $(RES)
LINKOBJ  = obj/bookmark.o obj/common.o obj/ds.o obj/editterm_win.o obj/frm_editterm.o obj/frm_telnet.o obj/login.o obj/main.o obj/scd_editterm.o obj/scd_gtk_textctrl.o obj/scd_socket.o obj/scd_tabctrl.o obj/scd_telnet.o obj/scd_terminal.o obj/telnet_panel.o $(RES)
LIBS =  -L"D:/Dev-Cpp/lib" -mwindows -Wl,--subsystem,windows -mwindows -lwxmsw -lstdc++ -lgcc -lodbc32 -lwsock32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lctl3d32 -ladvapi32 -lopengl32 -lglu32 -lole32 -loleaut32 -luuid    -s
INCS =  -I"D:/Dev-Cpp/include"
CXXINCS =  -I"D:/Dev-Cpp/include/c++"  -I"D:/Dev-Cpp/include/c++/mingw32"  -I"D:/Dev-Cpp/include/c++/backward"  -I"D:/Dev-Cpp/include"
BIN  = obj/BBMan.exe
CXXFLAGS = $(CXXINCS) -DWINVER=0x0400 -D__WIN95__ -D__GNUWIN32__ -D__WIN32__ -DHAVE_W32API_H  -D__WXMSW__ -D__WINDOWS__ -Wall -fno-pcc-struct-return -O2 -Os -fno-rtti -fno-exceptions   -fexpensive-optimizations -O2
CFLAGS = $(INCS) -D__WXMSW__   -fexpensive-optimizations -O2

.PHONY: all all-before all-after clean clean-custom

all: all-before obj/BBMan.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "obj\BBMan.exe" $(LIBS)

obj/bookmark.o: ../../src/bookmark.cpp
	$(CPP) -c ../../src/bookmark.cpp -o obj/bookmark.o $(CXXFLAGS)

obj/common.o: ../../src/common.cpp
	$(CPP) -c ../../src/common.cpp -o obj/common.o $(CXXFLAGS)


obj/ds.o: ../../src/ds.cpp
	$(CPP) -c ../../src/ds.cpp -o obj/ds.o $(CXXFLAGS)

obj/editterm_win.o: ../../src/editterm_win.cpp
	$(CPP) -c ../../src/editterm_win.cpp -o obj/editterm_win.o $(CXXFLAGS)

obj/frm_editterm.o: ../../src/frm_editterm.cpp
	$(CPP) -c ../../src/frm_editterm.cpp -o obj/frm_editterm.o $(CXXFLAGS)


obj/frm_telnet.o: ../../src/frm_telnet.cpp
	$(CPP) -c ../../src/frm_telnet.cpp -o obj/frm_telnet.o $(CXXFLAGS)

obj/login.o: ../../src/login.cpp
	$(CPP) -c ../../src/login.cpp -o obj/login.o $(CXXFLAGS)

obj/main.o: ../../src/main.cpp
	$(CPP) -c ../../src/main.cpp -o obj/main.o $(CXXFLAGS)

obj/scd_editterm.o: ../../src/scd_editterm.cpp
	$(CPP) -c ../../src/scd_editterm.cpp -o obj/scd_editterm.o $(CXXFLAGS)

obj/scd_gtk_textctrl.o: ../../src/scd_gtk_textctrl.cpp
	$(CPP) -c ../../src/scd_gtk_textctrl.cpp -o obj/scd_gtk_textctrl.o $(CXXFLAGS)

obj/scd_socket.o: ../../src/scd_socket.cpp
	$(CPP) -c ../../src/scd_socket.cpp -o obj/scd_socket.o $(CXXFLAGS)

obj/scd_tabctrl.o: ../../src/scd_tabctrl.cpp
	$(CPP) -c ../../src/scd_tabctrl.cpp -o obj/scd_tabctrl.o $(CXXFLAGS)

obj/scd_telnet.o: ../../src/scd_telnet.cpp
	$(CPP) -c ../../src/scd_telnet.cpp -o obj/scd_telnet.o $(CXXFLAGS)

obj/scd_terminal.o: ../../src/scd_terminal.cpp
	$(CPP) -c ../../src/scd_terminal.cpp -o obj/scd_terminal.o $(CXXFLAGS)

obj/telnet_panel.o: ../../src/telnet_panel.cpp
	$(CPP) -c ../../src/telnet_panel.cpp -o obj/telnet_panel.o $(CXXFLAGS)






















BBMan_private.res: BBMan_private.rc
	$(WINDRES) -i BBMan_private.rc -I rc -o BBMan_private.res -O coff  --include-dir D:/Dev-Cpp/include
